FROM alpine:3

LABEL author="Putri Oktatriani"
LABEL company="BestCarService" website="https://bestcarservice.netlify.app/"

RUN mkdir halo
RUN echo "Halo My Love" > "halo/world.txt"

CMD cat "halo/world.txt"